### ISSUE TITLE
Павленко Андрей Русланович

### ISSUE THREAD

**Issue by Andreypavlru** [vlasove/ING_Py_Sun_18#1]
[https://github.com/Andreypavlru/Domashka?files=1]()

**Comment by vlasove** [comment]
Андрей, а куда ведет эта ссылка?)
И поправь пожалуйста. 
Все решения лежат в **ОТДЕЛЬНЫХ** файлах в папке **HW_#**.Все файлы должны иметь расширение ```.py```

**Comment by vlasove** [comment]
После того, как файлы обновил - отпиши хотя бы об этом :)

**Comment by vlasove** [comment]
task1 --- зачтено

**Comment by vlasove** [comment]
task2 --- зачтено

**Comment by vlasove** [comment]
task3 --- зачтено

**Comment by vlasove** [comment]
task4 --- зачтено

**Comment by vlasove** [comment]
Красавчик!


**Зачет по ДЗ!**
