### ISSUE TITLE
Module 1

### ISSUE THREAD

**Issue by ARTIK0452** [vlasove/ING_Py_Sun_18#11]
Валов Артур Александрович
Модуль-1

https://github.com/ARTIK0452/module-1

**Comment by vlasove** [comment]
Работает хорошо, но в задании требуется, чтобы пользователь вводил название файла, в котором лежит текст. У тебя сделано название файла статичным. Поправь это и зачту

**Comment by ARTIK0452** [comment]
исправил

**Comment by vlasove** [comment]
Четко!

**Красавчик!**
