### ISSUE TITLE
ДЗ.n3 (Стругатский Роман)

### ISSUE THREAD

**Issue by Kormak7** [vlasove/ING_Py_Sun_18#12]
Стругатский Роман
https://github.com/Kormak7/Kormak.git

**Comment by vlasove** [comment]
Оу ноу,  я же говорил, линк на репозиторий с кодом. Не архивы же)

**Comment by vlasove** [comment]
task1 --- зачтено

**Comment by vlasove** [comment]
task2 --- зачтено

**Comment by vlasove** [comment]
task3 --- зачтено

**Comment by vlasove** [comment]
task4 --- зачтено

**Comment by vlasove** [comment]
Первая, конечно, очень загадочная, но тем не менее для первого раза ок.

**Зачет за дз**
