### ISSUE TITLE
Пфейфер Никита Юрьевич 

### ISSUE THREAD

**Issue by Nanoxia123** [vlasove/ING_Py_Sun_18#2]
https://github.com/Nanoxia123/homeworrk 
@vlasove

**Comment by vlasove** [comment]
task1 --- неверный формат вывода. В условии требуется выводить **только** ответ на задачу. Больше ничего не требовалось

**Comment by vlasove** [comment]
task2 --- зачтено

**Comment by vlasove** [comment]
task3 --- зачтено

**Comment by vlasove** [comment]
task4 --- неверный формат вывода. Проверь как требуется в **условии** .

**Comment by vlasove** [comment]
task1 -- зачтено

**Comment by vlasove** [comment]
task4 --- зачтено

**Comment by vlasove** [comment]
Неплохо

**Зачет по ДЗ!**
