### ISSUE TITLE
Нефёдов Никита Витальевич

### ISSUE THREAD

**Issue by nikita-vitalievich** [vlasove/ING_Py_Sun_18#3]
https://github.com/nikita-vitalievich/-brilliant-homework

**Comment by vlasove** [comment]
Скидывай пожалуйста не зип архив - а уже сразу файлы по дз с расширением ```.py```

**Comment by vlasove** [comment]
Внутри все правильно, но в следующий раз архив не приму!

**Зачет по ДЗ!**
