### ISSUE TITLE
Буяшкин Арсений романович

### ISSUE THREAD

**Issue by pernulmaslom** [vlasove/ING_Py_Sun_18#4]
https://github.com/pernulmaslom/ded

**Comment by vlasove** [comment]
task2 --- неверный формат вывода. Посмотри, сколько букв ```Ы```  требуется по условию

**Comment by vlasove** [comment]
task3 --- зачтено

**Comment by vlasove** [comment]
task4 --- зачтено

**Comment by pernulmaslom** [comment]
1 и 2 исправил

**Comment by vlasove** [comment]
task1 --- зачтено

**Comment by vlasove** [comment]
task2 --- зачтено

**Comment by vlasove** [comment]
Дз принял!
