### ISSUE TITLE
module 1

### ISSUE THREAD

**Issue by GiornoGiovanaJoJo** [vlasove/ING_Py_Sun_18#9]
`import re

f =  open('input.txt','r').read().lower()
pattern=re.findall(r'\b[a-z]{3,15}\b', f)
f.close()

d={}
for i in pattern:
    if i not in d.keys():
        if len(i)>3:
            d[i]=1
    else:
        d[i]+=1
list_d = list(d.items())
list_d.sort(key=lambda i: i[1],reverse=True)
a=[]
for i in range(5):
    a.append(list_d[i][0])
a.sort()
for i in a:
    print(i)`
(www.code.re/i61)

**Comment by vlasove** [comment]
Все супер! Зачет по модулю!
